name: Build Android Apps

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        directory: ['ASLRecognition', 'D2Go', 'HelloWorldApp', 'ImageSegmentation', 'NativeApp', 'ObjectDetection', 'PyTorchDemoApp', 'QuestionAnswering', 'Seq2SeqNMT', 'SpeechRecognition', 'StreamingASR', 'TorchVideo', 'ViT4MNIST']

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8

      - name: Install Gradle
        run: sudo apt-get install gradle

      - name: Build with Gradle
        run: |
          cd ${{ matrix.directory }}
          if [ ! -f "build.gradle" ]; then
            echo "No build.gradle in directory. Skipping..."
            exit 0
          fi
          if [ ! -f "gradlew" ]; then
            gradle wrapper --gradle-version 7.0
          fi
          chmod +x gradlew
          ./gradlew assembleDebug
