name: Build Android App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          repository: GuinnessShep/android-demo-app

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install SDKMAN and Gradle
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle

      - name: Update Android SDK
        run: |
          yes | sdkmanager --licenses
          sdkmanager --update

      - name: Build with Gradle
        run: |
          cd android-demo-app
          failed_dirs=()
          for dir in */; do
            if [ -f "$dir/build.gradle" ]; then
              echo "Building $dir"
              cd "$dir"
              chmod +x gradlew
              if [ ! -f "gradlew" ]; then
                gradle wrapper --gradle-version 7.0
              fi
              if ! ./gradlew build; then
                echo "Build failed for $dir. Downloading Gradle Wrapper..."
                rm -rf .gradle
                gradle wrapper --gradle-version 7.0
                ./gradlew build
              fi
              if [ -f "build/outputs/apk/debug/app-debug.apk" ]; then
                echo "Build succeeded for $dir"
              else
                echo "Build failed for $dir"
                failed_dirs+=("$dir")
              fi
              cd ..
            fi
          done
          if [ ${#failed_dirs[@]} -gt 0 ]; then
            echo "Failed directories: ${failed_dirs[*]}"
            exit 1
          fi
