name: Build Android App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Android Command-line Tools
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
          mkdir -p $HOME/cmdline-tools
          unzip commandlinetools-linux-6858069_latest.zip -d $HOME/cmdline-tools
          rm commandlinetools-linux-6858069_latest.zip
          echo "ANDROID_HOME=$HOME/cmdline-tools" >> $GITHUB_ENV
          echo "$HOME/cmdline-tools/tools/bin" >> $GITHUB_PATH

      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses

      - name: Update Android SDK
        run: $ANDROID_HOME/tools/bin/sdkmanager --update

      - name: Find and Download Missing Files
        run: |
          cd android-demo-app
          for dir in */; do
            if [ "$dir" != ".github/" ]; then
              cd "$dir"
              if [ ! -f "gradlew" ]; then
                echo "gradlew not found, downloading..."
                gradle_version=$(grep -oP "(?<=distributionUrl=).*" gradle/wrapper/gradle-wrapper.properties | sed "s/https\\:\\/\\/services\\.gradle\\.org\\/distributions\\/gradle-//g" | sed "s/-all\\.zip//g")
                gradle_wrapper_url="https://services.gradle.org/distributions/gradle-${gradle_version}-bin.zip"
                mkdir -p gradle/wrapper
                curl -o gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/blob/master/gradle/wrapper/gradle-wrapper.jar
                echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
                echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
                echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
                echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
                echo "distributionUrl=${gradle_wrapper_url}" >> gradle/wrapper/gradle-wrapper.properties
              fi
              cd ..
            fi
          done

      - name: Build with Gradle
        run: |
          cd android-demo-app
          for dir in */; do
            if [ "$dir" != ".github/" ]; then
              cd "$dir"
              if [ -f "build.gradle" ]; then
                chmod +x gradlew
                if ! ./gradlew build; then
                  echo "::error::Build failed for $dir, retrying..."
                  sleep 5
                  if ! ./gradlew build; then
                    echo "::error::Build still failing for $dir after retry, exiting..."
                    exit Apologies, it seems the response got cut off. Here's the completed part of the yaml file:

```yaml
                    exit 1
                  fi
                else
                  echo "Build succeeded for $dir"
                fi
                rm -rf .gradle
              fi
              cd ..
            fi
          done
