name: Advanced Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Android SDK
        uses: malinskiy/action-android/sdk-install@0.1.0
        with:
          api-level: 30
          build-tools-version: 30.0.3

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run Gradle build
        run: |
          set -e

          function handle_error {
            echo "::error::Build failed! Attempting to gather additional details..."
            ./gradlew tasks --all
            ./gradlew --status
            ./gradlew buildEnvironment
            ./gradlew dependencyInsight --configuration compileClasspath --dependency $1
            echo "::error::Finished gathering details. Please review the output above for additional information."
            exit 1
          }

          trap 'handle_error $?' ERR

          echo "Building project..."
          ./gradlew build
