name: Build Android Apps

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: ['ASLRecognition', 'D2Go', 'HelloWorldApp', 'ImageSegmentation', 'NativeApp', 'ObjectDetection', 'PyTorchDemoApp', 'QuestionAnswering', 'Seq2SeqNMT', 'SpeechRecognition', 'StreamingASR', 'TorchVideo', 'ViT4MNIST']

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install SDKMAN and Gradle
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle

      - name: Build with Gradle
        run: |
          cd ${{ matrix.directory }}
          if [ ! -f "gradlew" ]
          then
            gradle wrapper
          fi
          chmod +x gradlew
          ./gradlew build
