name: Build Gradle Apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: 'gradle' 

    - name: Install SDKMAN and Gradle
      run: |
        curl -s "https://get.sdkman.io" | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install gradle 5.6.2

    - name: Prepare and build with Gradle
      run: |
        find . -name "build.gradle" -not -path "./build/*" -exec dirname {} \; | while read dir; do
          pushd "$dir"
          gradle wrapper
          ./gradlew init
          ./gradlew clean build
          popd
        done
      shell: bash

    - name: Catch errors
      if: ${{ failure() }}
      run: echo "The build was not successful. Please check the logs above for the error message."

    - name: Success message
      if: ${{ success() }}
      run: echo "The build was successful. Congratulations!"
