name: Build Android Apps

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: ['ASLRecognition', 'D2Go', 'HelloWorldApp', 'ImageSegmentation', 'NativeApp', 'ObjectDetection', 'PyTorchDemoApp', 'QuestionAnswering', 'Seq2SeqNMT', 'SpeechRecognition', 'StreamingASR', 'TorchVideo', 'ViT4MNIST']

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Gradle
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle

      - name: Build with Gradle
        run: |
          if [ -f "${{ matrix.directory }}/build.gradle" ]
          then
            cd ${{ matrix.directory }}
            gradle build
          else
            echo "No gradle build file in ${{ matrix.directory }}, skipping..."
          fi
