name: Android CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Run Gradle Wrapper and Clean
      run: |
        for d in *; do
          if [ -d "$d" ]; then
            cd "$d"
            if [ -f "./gradlew" ]; then
              chmod +x ./gradlew
              ./gradlew wrapper --gradle-version=5.6.2
              ./gradlew init
              ./gradlew clean
            fi
            cd ..
          fi
        done

    - name: Build with Gradle
      run: |
        for d in *; do
          if [ -d "$d" ]; then
            cd "$d"
            if [ -f "./gradlew" ]; then
              ./gradlew build
            fi
            cd ..
          fi
        done

    - name: Handle build failure
      if: ${{ failure() }}
      run: echo "There were errors during the build process."
